import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import NavbarView from "@/components/navbar/Navbar.view";
import FooterView from "@/components/footer/footer.view";

const geistSans = Geist({
     variable: "--font-geist-sans",
     subsets: ["latin"],
});

const geistMono = Geist_Mono({
     variable: "--font-geist-mono",
     subsets: ["latin"],
});

export const metadata: Metadata = {
     title: "Create Next App",
     description: "Generated by create next app",
};

export default function RootLayout({
     children,
}: Readonly<{
     children: React.ReactNode;
}>) {
     return (
          <html lang="en">
               <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                    <NavbarView />
                    <div className="body-item">{children}</div>
                    <FooterView />
               </body>
          </html>
     );
}
